[book]
authors = ["Marcos Brito"]
language = "en"
multilingual = false
src = "src"
title = "Henactor docs"

[output.html]
git-repository-url = "https://github.com/marcos-brito/henactor"
site-url = "/henactor/"
